Update README.md on PCL dependency
Ericsii/FAST_LIO pull request #4
Opened 2023-12-29 01:32 UTC by AzulRadio

Hi, thanks for the amazing work on porting FAST_LIO to ROS2!

I'm deploying FAST_LIO on an Nvidia Jetson with Ubuntu 22.04 and ROS 2 Humble and I found some disagreement between the README instructions and what actually happened. So I add my solution to the README.

Changes: 
- The PCL default from apt (`libpcl-dev`) doesn't work for me and FAST_LIO refuses to compile. After I installed `pcl_ros` the problem was fixed.
- The link for PCL installation no longer directs to a 404 site.

Jetson might not be the hardware people use the most to deploy FAST_LIO so I don't know if the problem is just for ARM arch or everyone. It would be nice if someone could help me verify this.

Thanks again for your work!

2023-12-29 09:34 UTC, Ericsii commented
Much appreciate your contribution. @AzulRadio

This `README.md` change makes great sense. But I have another question.

> - The PCL default from apt (`libpcl-dev`) doesn't work for me and FAST_LIO refuses to compile. After I installed pcl_ros the problem was fixed.

You said the `libpcl-dev` from apt is not compatible with Jetson. If so, there should be a change in the `package.xml` file to fix the dependency problem. Can you provide a detailed build log?

2023-12-29 10:05 UTC, AzulRadio commented
@Ericsii Here you go
```
Starting >>> fast_lio
--- stderr: fast_lio
Current CPU archtecture: aarch64
CMake Error at CMakeLists.txt:60 (find_package):
  By not providing "Findpcl_ros.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "pcl_ros", but
  CMake did not find one.

  Could not find a package configuration file provided by "pcl_ros" with any
  of the following names:

    pcl_rosConfig.cmake
    pcl_ros-config.cmake

  Add the installation prefix of "pcl_ros" to CMAKE_PREFIX_PATH or set
  "pcl_ros_DIR" to a directory containing one of the above files.  If
  "pcl_ros" provides a separate development package or SDK, be sure it has
  been installed.


---
Failed   <<< fast_lio [2.16s, exited with code 1]

Summary: 0 packages finished [3.87s]
  1 package failed: fast_lio
  1 package had stderr output: fast_lio

```

2024-01-01 06:33 UTC, Ericsii commented
It seems you didn't use `rosdep install --from-paths src --ignore-src -y` this command to install dependencies. 
Can you help me add this line to `README.md`?

2024-01-01 06:38 UTC, Ericsii requested changes

2024-01-01 06:38 UTC, Ericsii commented on README.md
> +For PCL, if the default from apt `libpcl-dev` doesn't work for you, try to install `pcl_ros` with `sudo apt install ros-<ros2-distro>-pcl-ros` instead.
This line should be deleted by using `rosdep` to handle the dependencies. Meanwhile add a new line `rosdep install --from-paths src --ignore-src -y` before line 96 `colcon build --symlink-install`.

2024-01-01 07:20 UTC, AzulRadio commented on README.md
> +For PCL, if the default from apt `libpcl-dev` doesn't work for you, try to install `pcl_ros` with `sudo apt install ros-<ros2-distro>-pcl-ros` instead.
Resolved in 5e0a012943da93bf58fdc357afe4e428321f3554

2024-01-01 10:06 UTC, Ericsii approved these changes

2024-01-01 10:06 UTC, Ericsii commented
LGTM

2024-01-01 10:06 UTC, merged